### Sign Up request
POST http://localhost:8000/signup

{
  "username": "johndoe",
  "password": "mysecurepassword"
}

### Signin request with correct password

POST http://localhost:8000/signin

{
  "username": "johndoe",
  "password": "mysecurepassword"
}

### Signin request with incorrect password

POST http://localhost:8000/signin

{
  "username": "johndoe",
  "password": "incorrect"
}